services:
  - type: web
    name: gymjam2026
    env: static
    staticPublishPath: .
    buildCommand: ""
    routes:
      - type: rewrite
        source: /u1314
        destination: /u1314/index.html
      - type: rewrite
        source: /u1314/
        destination: /u1314/index.html
      - type: rewrite
        source: /u1516
        destination: /u1516/index.html
      - type: rewrite
        source: /u1516/
        destination: /u1516/index.html
